[workspace]

members = [
    "entries-job-scheduler",
    "entries-server",
    "entries-utils",
]

[workspace.package]
authors = ["Tanner Davies"]
version = "0.1.0"
edition = "2021"

[profile.release]
lto = "thin"