# This configuration is for testing purposes only

[connections]
database_uri = "postgres://entriesdbuser:0Psrku4jzIRi5mD0ctOB@localhost/entries_test"
max_db_connections = 20

[runner]
update_frequency_secs = 5
worker_threads = 2
max_blocking_threads = 60

[clear_expired_budget_invites_job]
job_frequency_secs = 43200

[clear_expired_otps_job]
job_frequency_secs = 900

[clear_old_user_deletion_requests_job]
job_frequency_secs = 3540

[clear_throttle_table_job]
job_frequency_secs = 86400

[clear_unverified_users_job]
job_frequency_secs = 86400
max_unverified_user_age_days = 7

[delete_users_job]
job_frequency_secs = 86400

[unblacklist_expired_tokens_job]
job_frequency_secs = 172800
