# This configuration is for testing purposes only

[db]
database_uri = "postgres://entriesdbuser:0Psrku4jzIRi5mD0ctOB@localhost/entries_test"
# If omitted, defaults to 4 * CPU count
max_db_connections = 48
# If omitted, defaults to 25 secs
db_idle_timeout_secs = 25

[hashing]
hash_iterations = 2
hash_length = 32
hash_mem_size_kib = 128
hash_lanes = 1
salt_length_bytes = 16

[email]
email_enabled = false
from_address = "Entries App <no-reply@entriesapp.com>"
reply_to_address = "Entries App Support <support@entriesapp.com>"
smtp_address = "email-smtp.us-west-2.amazonaws.com"
# If omitted, defaults to 2 * CPU count
max_smtp_connections = 24
# If omitted, defaults to 25 secs
smtp_idle_timeout_secs = 25

# To generate secure random key and convert to base 64:
# dd if=/dev/urandom bs=64 count=1 2>/dev/null | base64
# where bs is the number of bytes in the key
[keys]
hashing_key_b64 = "KEY" # 32 bytes
token_signing_key_b64 = "KEY" # 64 bytes
token_encryption_key_b64 = "KEY" # 16 bytes
amazon_ses_username = "USERNAME"
amazon_ses_key = "KEY"

[lifetimes]
access_token_lifetime_mins = 8
refresh_token_lifetime_days = 28
signin_token_lifetime_mins = 11
user_creation_token_lifetime_days = 7
user_deletion_token_lifetime_days = 3
otp_lifetime_mins = 5

[time_delays]
user_deletion_delay_days = 7

[workers]
# If omitted, defaults to CPU count
actix_workers = 12
