# This configuration is for testing purposes only
# Secrets in this file aren't real secrets

[db]
database_uri = "postgres://entriesdbuser:0Psrku4jzIRi5mD0ctOB@localhost/entries_test"
max_db_connections = 48
db_idle_timeout_secs = 25

[hashing]
hash_iterations = 2
hash_length = 32
hash_mem_cost_kib = 128
hash_threads = 1
salt_length = 16

[email]
email_enabled = false
from_address = "Entries App <no-reply@entriesapp.com>"
reply_to_address = "Entries App Support <support@entriesapp.com>"
smtp_address = "[redacted]"
# If omitted, defaults to 2 * CPU count
max_smtp_connections = 24
smtp_idle_timeout_secs = 25

[endpoints]
user_verification_url = "http://127.0.0.1:9000/user/verify_creation"
user_deletion_url = "http://127.0.0.1:9000/user/delete"

# These need to be changed in production
[keys]
hashing_key_b64 = "DxftwcsQpY3abXLcPZx93E7wwhIKdqoRoQ9YxmAyRWE=" # 32 bytes
token_signing_key_b64 = "sTBPAz+FCvty/nSFmsFOEy749cFoT7KzgmBbht0w3y6FSZNI9eOyT8+CeiiO0a15AZZedWWsV18L7hymA8usXw==" # 64 bytes
token_encryption_key_b64 = "JIxcJ855KUBS8hj0+ki7rQ==" # 16 bytes
amazon_ses_username = "[redacted]"
amazon_ses_key = "[redacted]" # For the AWS us-west-2 region only

[lifetimes]
access_token_lifetime_mins = 8
refresh_token_lifetime_days = 28
signin_token_lifetime_mins = 11
user_creation_token_lifetime_days = 7
user_deletion_token_lifetime_days = 3
otp_lifetime_mins = 5

[logging]
log_level = "info"

[time_delays]
user_deletion_delay_days = 7

[workers]
actix_workers = 12
