use actix_web::web::*;

use crate::handlers::user;

use super::RateLimiters;

pub fn configure(cfg: &mut ServiceConfig, limiters: RateLimiters) {
    cfg.service(
        scope("/user")
            .service(
                resource("")
                    .route(
                        post()
                            .to(user::create)
                            .wrap(limiters.expensive_auth_fair_use.clone())
                            .wrap(limiters.expensive_auth_circuit_breaker.clone()),
                    )
                    .route(
                        delete()
                            .to(user::init_delete)
                            .wrap(limiters.light_auth_fair_use.clone())
                            .wrap(limiters.light_auth_circuit_breaker.clone()),
                    ),
            )
            .service(
                resource("/public-key")
                    .route(
                        get()
                            .to(user::lookup_user_public_key)
                            .wrap(limiters.read_fair_use.clone())
                            .wrap(limiters.read_circuit_breaker.clone()),
                    )
                    .route(
                        put()
                            .to(user::rotate_user_public_key)
                            .wrap(limiters.modify_fair_use.clone())
                            .wrap(limiters.modify_circuit_breaker.clone()),
                    ),
            )
            .service(
                resource("/preferences").route(
                    put()
                        .to(user::edit_preferences)
                        .wrap(limiters.modify_fair_use.clone())
                        .wrap(limiters.modify_circuit_breaker.clone()),
                ),
            )
            .service(
                resource("/keystore").route(
                    put()
                        .to(user::edit_keystore)
                        .wrap(limiters.modify_fair_use.clone())
                        .wrap(limiters.modify_circuit_breaker.clone()),
                ),
            )
            .service(
                resource("/password").route(
                    put()
                        .to(user::change_password)
                        .wrap(limiters.expensive_auth_fair_use.clone())
                        .wrap(limiters.expensive_auth_circuit_breaker.clone()),
                ),
            )
            .service(
                resource("/recovery-key").route(
                    put()
                        .to(user::change_recovery_key)
                        .wrap(limiters.expensive_auth_fair_use.clone())
                        .wrap(limiters.expensive_auth_circuit_breaker.clone()),
                ),
            )
            .service(
                resource("/email").route(
                    put()
                        .to(user::change_email)
                        .wrap(limiters.light_auth_fair_use.clone())
                        .wrap(limiters.light_auth_circuit_breaker.clone()),
                ),
            )
            .service(
                resource("/deletion")
                    .route(
                        get()
                            .to(user::is_listed_for_deletion)
                            .wrap(limiters.read_fair_use.clone())
                            .wrap(limiters.read_circuit_breaker.clone()),
                    )
                    .route(
                        delete()
                            .to(user::cancel_delete)
                            .wrap(limiters.modify_fair_use.clone())
                            .wrap(limiters.modify_circuit_breaker.clone()),
                    ),
            )
            .service(
                resource("/deletion/verify").route(
                    get()
                        .to(user::delete)
                        .wrap(limiters.light_auth_fair_use)
                        .wrap(limiters.light_auth_circuit_breaker),
                ),
            ),
    );
}
