[connections]
database_uri = "postgres://budgetappdbuser:0Psrku4jzIRi5mD0ctOB@localhost/budgetapp_test"
max_db_connections = 24

[runner]
# update_frequency_secs = 300
update_frequency_secs = 1

[clear_otp_attempts_job]
# job_frequency_secs = 14400
job_frequency_secs = 5

[clear_password_attempts_job]
# job_frequency_secs = 14400
job_frequency_secs = 8