# This configuration is for testing purposes only

[connections]
database_uri = "postgres://budgetappdbuser:0Psrku4jzIRi5mD0ctOB@localhost/budgetapp_test"
max_db_connections = 8

[runner]
update_frequency_secs = 10
worker_threads = 2
max_blocking_threads = 32

[clear_otp_attempts_job]
job_frequency_secs = 120 
attempts_lifetime_mins = 15

[clear_password_attempts_job]
job_frequency_secs = 120
attempts_lifetime_mins = 15

[delete_users_job]
job_frequency_secs = 86400 # One day

[unblacklist_expired_refresh_tokens_job]
job_frequency_secs = 86400 # One day
