# This configuration is for testing purposes only

[connections]
database_uri = "postgres://budgetappdbuser:0Psrku4jzIRi5mD0ctOB@localhost/budgetapp_test"
max_db_connections = 8

[runner]
update_frequency_secs = 5
worker_threads = 2
max_blocking_threads = 60

[clear_unverified_users_job]
job_frequency_secs = 86400
max_unverified_user_age_days = 7

[delete_users_job]
job_frequency_secs = 86400

[unblacklist_expired_tokens_job]
job_frequency_secs = 86400
